### ISSUE TITLE
New logo for faces

### ISSUE THREAD

**Issue by reallinfo** [HackerManifesto/faces#1]
Hello, I wanted to contribute to faces. I designed a logo for it. If you like it, I will send you a pr.

![faces](https://user-images.githubusercontent.com/36298335/39789338-ecb8cade-5337-11e8-939a-c33bab7af625.jpg)

**Comment by reallinfo** [comment]
Oh, okay. I sent a pr. 

https://github.com/HackerManifesto/faces/pull/2

**Comment by jbampton** [comment]
Merged by #2

**Comment by reallinfo** [comment]
thank you very much! :)
